# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nick Learns things
email: nick.a.eddy@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A mostly front-end development blog by a self-taught devloper.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: NickEddySplit
github_username:  OctoNerd

# Build settings
markdown: kramdown
